#' Create manifest of local files/directories to upload
#'
#' @param path a vector of file paths for local files and directories
#' @param recurse determines whether directories in `path` are recursed
#' @return data.frame of file metadata generated by `fs::file_info`, with the
#'   the following additional columns: `remote_path` and `remote_dir`
#' @noRd
.upload_manifest <- function(path, recurse) {
  stopifnot(rlang::is_scalar_vector(path))

  if (fs::is_dir(path)) {
    targets <- fs::dir_ls(path, type = c("file", "directory"), recurse = recurse)
  } else {
    targets <- path
  }

  inventory <- fs::file_info(targets)

  # the leaf directory of `path` will be the base destination for uploads
  inventory$remote_path <- fs::path_rel(inventory$path, dirname(path))
  inventory$remote_dir <- ifelse(
    inventory$type == "file",
    dirname(inventory$remote_path),
    identity(inventory$remote_path)
  )

  inventory
}

#' File transfer messages
#'
#' Generate messages about file conflicts while uploading or downloading.
#' @param filename Name of the file to be transferred
#' @param direction Label indicating whether the transfer was `"uploading"` or
#'   `"downloading`
#' @noRd

stop_conflict <- function(filename, direction) {
  msg <- bullet_msg(
    sprintf("Can't %s file '%s'.", direction, basename(filename)),
    c(
      "A file with the same name already exists at the destination.",
      "Use the `conflicts` argument to avoid this error in the future."
    )
  )
  abort(msg)
}

warn_ul_conflict <- function(filename) {
  msg <- bullet_msg(
    sprintf("Local file '%s' was NOT uploaded to OSF.", filename),
    c(
      "A file with the same name already exists at the destination.",
      "Use the `conflicts` argument to avoid this error in the future."
    )
  )
}


#' Succinct message indicating number of files uploaded or skipped
#' @param x an `osf_tbl_file` with the additional `.uploaded` column
#' @noRd
report_ul_activity <- function(x) {
  if (any(x$.uploaded))
    message(sprintf("Uploaded %i file(s) to OSF", sum(x$.uploaded)))
  if (any(!x$.uploaded))
    message(sprintf(
      "Skipped %i files to avoid overwriting OSF copies",
      sum(!x$.uploaded)
    ))
}
